### ISSUE TITLE
Typo in menuItem

### ISSUE THREAD

**Issue by draustus** [simonmeusel/MuteSpotifyAds#12]
Title should be "➤  Notifications" at https://github.com/simonmeusel/MuteSpotifyAds/blob/master/MuteSpotifyAds/Base.lproj/MainMenu.xib#L46

**Comment by qmnl** [comment]
This issue is fixed in code, but is not released yet. See #14

**Comment by qmnl** [comment]
Released at https://github.com/simonmeusel/MuteSpotifyAds/releases
