### ISSUE TITLE
Spotify get into my main screen when it restart

### ISSUE THREAD

**Issue by shawnloh** [simonmeusel/MuteSpotifyAds#17]
Whenever Spotify restart to skip the advertisement, the Spotify will come and disrupt my main screen, any way to keep it in the background? Great tool btw :)

**Comment by qmnl** [comment]
I tried to resolve this with https://github.com/simonmeusel/MuteSpotifyAds/commit/034c22f2f87ea26f371cbd1c9733e1523a62a5ef by adding the `--hide` flag to the `open` command, but that did indeed not fix it. There also seems to be the `--background` flag, so I'm going to try that one.

**Comment by qmnl** [comment]
Try this one: https://github.com/simonmeusel/MuteSpotifyAds/releases

**Comment by SensehacK** [comment]
@simonmeusel  Is this fixed or still open ? 
As I did got it reproduced in Mac OS Mojave ( When it restarted to skip ads ).
I'm on v1.11.0

**Comment by qmnl** [comment]
It should be fixed and it works for me. I don't think what could be done to further force Spotify to the background.

**Comment by SensehacK** [comment]
Maybe this command helps to invoke "Spotify" app in background.

"open -g /Applications/spotify.app"

**Comment by qmnl** [comment]
We currently use `/usr/bin/open --hide --background -b com.spotify.client`.

`-g` is the same as `--background`:

> Help: Open opens files from a shell.
> [...]
> -j, --hide        Launches the app hidden.
> -g, --background  Does not bring the application to the foreground.
> [...]
