### ISSUE TITLE
Application does not start correctly

### ISSUE THREAD

**Issue by xpiero** [simonmeusel/MuteSpotifyAds#19]
The first time I installed the app I could see the * at the status bar.
After I restarted the Mac, everytime I open the app, Spotify launches but the * never appear and the app doesn't seem to work anymore.

**Comment by xpiero** [comment]
I could make it appear again by deleting app preferences in Library -> Preferences.
but idk if this is normal.

**Comment by qmnl** [comment]
Thank you for reporting this issue.

It seems that the application fails to launch because of an invalid preference file. Does the issue still occur?

If so, can you run the command
```
/Applications/MuteSpotifyAds.app/Contents/MacOS/MuteSpotifyAds
```
from the Terminal and post the output? The command will start the application and log errors.

**Comment by shawnloh** [comment]
Happens to me too. When i tried to run /Applications/MuteSpotifyAds.app/Contents/MacOS/MuteSpotifyAds, it said that the process is killed

**Comment by dominicrutk** [comment]
I had this issue too, but manually reinstalling the latest version seemed to fix it.

**Comment by truebit** [comment]
> Thank you for reporting this issue.
> 
> It seems that the application fails to launch because of an invalid preference file. Does the issue still occur?
> 
> If so, can you run the command
> 
> ```
> /Applications/MuteSpotifyAds.app/Contents/MacOS/MuteSpotifyAds
> ```
> 
> from the Terminal and post the output? The command will start the application and log errors.

I installed latest version and got the same symptom here. run the commands from terminal did not get any output, spotify just launches, but ads occurr.

**Comment by xtealer** [comment]
Didn't see the icon so got it uninstalled. Got it installed again and just ran that command, now it launched and seems to be working just fine, didn't get that "process killed". Further testing is required.

**UPDATE**
After the  spotify restart it crashed, here are the logs i got with the command:
```bash
MuteSpotifyAds v1.9.0
macOS Version 10.14.5 (Build 18F132))
35:46: execution error: Spotify got an error: Connection is invalid. (-609)
35:46: execution error: Spotify got an error: Connection is invalid. (-609)
35:46: execution error: Spotify got an error: Connection is invalid. (-609)
```

**Comment by xpiero** [comment]
Well it happened again but this time Spotify doesn't even launch, I ran the command and I got:
`Killed: 9`

**Comment by cfvescovo** [comment]
In the next days I will debug and test the app. I will let you know if I manage to get it working

**Comment by cfvescovo** [comment]
It seems it's working well on my Mac

**Comment by cfvescovo** [comment]
@xpiero It seems to work correctly in 1.10

**Comment by qmnl** [comment]
I'm going to close this is as I don't have enough information to fix it and don't know if it still occurs. If you want to add anything, reopen or open a new issue.
