### ISSUE TITLE
Launch MuteSpotifyAds without auto-launching Spotify

### ISSUE THREAD

**Issue by mariobrostech** [simonmeusel/MuteSpotifyAds#20]
Hi,

I would like to make MuteSpotifyAds a startup app on my Mac, but when this happens, Spotify always opens in the foreground automatically. My request is that this is provided as a preference in the application so that it doesn't interfere with some users' startup tasks.

Thank you for taking this request into consideration.

**Comment by cfvescovo** [comment]
I will work on your request

**Comment by mariobrostech** [comment]
> I will work on your request

Thank you very much! Please post back here when it's implemented.

**Comment by cfvescovo** [comment]
I worked on it but it isn't working well actually. I will debug it, fix it and open a PR

**Comment by qmnl** [comment]
Released with v1.10.0: https://github.com/simonmeusel/MuteSpotifyAds/releases
