### ISSUE TITLE
Quitting Spotify together with MuteSpotifyAds

### ISSUE THREAD

**Issue by lbordino** [simonmeusel/MuteSpotifyAds#22]
A friend of mine @BaldEagleX02  suggested me this app, it's really useful but, in my opinion, it should close both Spotify and itself when a user quits it.(with a clickable checkbox like every other option)
I've downloaded the  repo and already made the change for myself, if you want to add this feature I can send or upload the files.
<img width="211" alt="Screenshot 2019-09-06 at 20 23 19" src="https://user-images.githubusercontent.com/37419534/64451374-5fce7e80-d0e4-11e9-888e-7f63117ca638.png">

**Comment by cfvescovo** [comment]
@lbordino Fork this repo and open a PR

**Comment by qmnl** [comment]
See #23

**Comment by qmnl** [comment]
Released with `v1.11.0`: https://github.com/simonmeusel/MuteSpotifyAds/releases
