### ISSUE TITLE
Ads get paused

### ISSUE THREAD

**Issue by qmnl** [simonmeusel/MuteSpotifyAds#3]

**Comment by qmnl** [comment]
Seems to be a issue with Spotify, since this also happend to me when not muting the ads

**Comment by qmnl** [comment]
A possible fix would be to auto resume the ad, which would require polling when the ads play silently.

**Comment by qmnl** [comment]
The fix in 19bf8c2fb93ca35130b55549824d2c90eda24646 seems to work for me, if ads still get stuck for anyone, just open another issue!

**Comment by qmnl** [comment]
Released, see https://github.com/simonmeusel/MuteSpotifyAds/releases

Download: https://github.com/simonmeusel/MuteSpotifyAds/releases/download/v1.3.1/MuteSpotifyAds.app.zip

**Comment by Moulde** [comment]
This seems to require mac 10.13? :(

**Comment by qmnl** [comment]
@Moulde What version are you on (Please answer at #6)? See #6
