### ISSUE TITLE
On restart Spotify skips to the next song

### ISSUE THREAD

**Issue by MarpinLL** [simonmeusel/MuteSpotifyAds#32]
When an add is detected the program restarts and plays the next song in Spotify instead of the one that was actually going to be played.

**Comment by qmnl** [comment]
First of all, thank you for creating this issue.

Actually we're pretty lucky that Spotify somewhat remembers what to play next.

But implementing a fix to this issue would take quite some time and would heavily increase the complexity of this application. We would somehow need to query the UI and click the song queue button, and somehow tell Spotify what song to play next. I think this is to much for this application.

Instead, you may use the `mute` mode.

**Comment by qmnl** [comment]
If anyone has a better idea for a fix, you can comment.

Pull requests correctly implementing this are also welcome.
