### ISSUE TITLE
Playback does not automatically start upon restart

### ISSUE THREAD

**Issue by whosfromthegreatstate** [simonmeusel/MuteSpotifyAds#33]
Spotify restarts automatically, but once it restarts it does not resume playing.  Is there a way for it to automatically play upon restart?

**Comment by qmnl** [comment]
Thanks for reporting this issue normally Spotify should continue playing after restarting. If the Spotify takes too long to start up though, it might not resume. I will try to fix that and make it independent of the hardware specs.

For now you can disable the restart mode.

**Comment by qmnl** [comment]
Fixed with v1.11.2

**Comment by whosfromthegreatstate** [comment]
Thank you!
