### ISSUE TITLE
Spotify bug causing ads to get stuck

### ISSUE THREAD

**Issue by qmnl** [simonmeusel/MuteSpotifyAds#4]
Because of this bug in Spotify we need polling every 4 seconds, when the ads are playing. Every 4 seconds the ad gets playpaused two times and will thus continue to play if stuck.

**Comment by qmnl** [comment]
See #3

**Comment by qmnl** [comment]
This issue track the Spotify bug, whereas #3 is about the hotfix

**Comment by qmnl** [comment]
If this bug gets fixed, the TODOs in the source code have to be removed and the notice in the `README.md` has to be removed.

**Comment by qmnl** [comment]
Spotify still has the issue in `1.0.89.313.g34a58dea`

**Comment by dwightmulcahy** [comment]
Hmmmm.... I'm still seeing this issue on v1.4.1... ad gets stuck and keeps backing up 4secs on the pause/play.

**Comment by qmnl** [comment]
I think the issue has nothing to do with MuteSpotifyAds.

But because the ads got stuck in Spotify, I added a feature which pause/plays every 4 seconds, to fix the Spotify issue

**Comment by cfvescovo** [comment]
This issue is solved in v 1.5 thanks to the restart spotify feature. I am still seeing it when using standard mode. 
I think the restart  spotify mode should become the default mode.

**Comment by qmnl** [comment]
> I think the restart spotify mode should become the default mode.

I won't make it the default mode, because:

1. The name of the app `MuteSpotifyAds` wouldn't fit anymore
2. It would ruin the Spotify buisness model, because they receive no ad revenue when this mode is enabled

Thus I will leave it as a option for those who would like to enable it.

**Comment by cfvescovo** [comment]
Yeah, I was not thinking about Spotify's economical model. You are right. They pay authors in order to be able to share their music. It would be very unfair for Spotify.

**Comment by qmnl** [comment]
I think the issue should now be fixed by Spotify, I'm gonna adjust the application in the next release.
