### ISSUE TITLE
Support for older MacOS versions

### ISSUE THREAD

**Issue by qmnl** [simonmeusel/MuteSpotifyAds#6]
Currently the deployment target is 10.13

**Comment by qmnl** [comment]
Adding support for 10.12 would be easy. For 10.11 it would require some minor code changes

**Comment by Moulde** [comment]
I'm on 10.12.6 - so support for 10.12 would be great imo :)
I tend to stay ~1 major release behind for OSX

**Comment by qmnl** [comment]
Staying on major behind isn't such a bad idea, if I look back at the update progress, because the update caused my system no not boot anymore, because I had FileVault enabled. But I had a TimeMachine backup 😨 .

Ok I'm going to set the target to 10.12

**Comment by qmnl** [comment]
Implemented with e64d0aab0cd9187ff2384eb5cdf070ec8895f2c0

**Comment by qmnl** [comment]
Released: https://github.com/simonmeusel/MuteSpotifyAds/releases

**Comment by Moulde** [comment]
@simonmeusel Great thanks! 👍 
Yeah, it's pretty crap that it's necessary to stay behind updates because of issues.
Real men don't do backups, but they do tend to cry more... :)

**Comment by xhruso00** [comment]
Is it also possible to make xcodeproj compatible with XCode 9.2? XIB can be opened but I can't open the project. Currently it is set to 9.3.1. Thanks!

**Comment by qmnl** [comment]
@xhruso00 Sorry, but It's not my goal to make it compatible with old development tools in general, since old versions may house security issues or generally lack features. And I think the developers should be able to keep their software up to date.

I there any reason why you don't upgrade your XCode or install many versions of it?

**Comment by xhruso00** [comment]
I am on 10.12. and the highest XCode is 9.2. I just can't open Xcode as project. Beside you must use Swift 4.2 which Xcode 9.2 doesn't support. There is no need to make it compatible at all.
