### ISSUE TITLE
Restart Spotify

### ISSUE THREAD

**Issue by cfvescovo** [simonmeusel/MuteSpotifyAds#7]
Could your application restart Spotify instead of muting it? I am asking for this feature because Spotifree implemented it in version 2.0dev2 and I think it is very useful. In fact if you restart Spotify while an ad is playing Spotify skips it and starts playing the following song.

Thank you for your work!

**Comment by qmnl** [comment]
That's great idea, maybe I will add a option for it if i find time

**Comment by cfvescovo** [comment]
I think you should only add this code when your app sees Spotify is playing an ad.
```
tell application "Spotify"
     quit
end tell
delay 2
tell application "Spotify" to activate
delay 2
tell application "System Events"
    tell process "Spotify"
        click menu item "Play" of menu "Playback" of menu bar 1
    end tell
end tell
```

**Comment by qmnl** [comment]
I have implemented it with 4049fb70ba1d14e46e2c067a0b9065bb4ba34be8. I'm going to test it a litte more, add the docs, and then create a new release.

I have still packaged it so you can try it as well:
[MuteSpotifyAds.app.zip](https://github.com/simonmeusel/MuteSpotifyAds/files/2592968/MuteSpotifyAds.app.zip)

**Comment by qmnl** [comment]
I made some adjustments and it seems to work.

**Comment by cfvescovo** [comment]
Yeah, thank you! I am very happy to be a contributor of this interesting project!

**Comment by cfvescovo** [comment]
I will test the app this afternoon

**Comment by cfvescovo** [comment]
It works very well! 
I hope you will publish the new version of the application soon! 
If you need help feel free to contact me. 
I am glad to help this project to grow with some new features.

**Comment by qmnl** [comment]
Released: https://github.com/simonmeusel/MuteSpotifyAds/releases
