### ISSUE TITLE
Use travis-ci to auto-build nightlies

### ISSUE THREAD

**Issue by erseco** [simonmeusel/MuteSpotifyAds#8]
Can be useful autobuild the project to allow people to use the latest nightly code

**Comment by qmnl** [comment]
I have tried something like this with some XCode project, but I had troubles with the Code Signing. But it would be convenient. Maybe I'll try it again.

**Comment by erseco** [comment]
You can add your codesigning keys as *secret* env vars, like here https://www.jviotti.com/2016/03/16/how-to-code-sign-os-x-electron-apps-in-travis-ci.html I can help you if you need :) 

Thanks for the app!

**Comment by qmnl** [comment]
The article is very helpful. Thank you.

But currently I don't want implement this, as it would also require a way to upload the archive somewhere or automatically attach it to a release. See https://stackoverflow.com/questions/45240336/how-to-use-github-release-api-to-make-a-release-without-source-code
